io.mend.sast.exception.DatabaseException#instance-init#